### ISSUE TITLE
why mine is not like this sample?

### ISSUE THREAD

**Issue by townmi** [NativeScript/sample-Tasks#2]
I have clone this project to my local, then I build an deplay on my device. but it's ui so ugly. no icons, no bg-color; and buttons not full-screen, not like sample.

most important, how can i remove that top-bar(with a naticescript logo).

when we use back-button in brower,that's meaning we need go to previous page , but in apps mybe we need to close app.

**Comment by valentinstoychev** [comment]
Hi, this is the first version of the app and not the entire functionality is implemented. We are working actively on it and updating the source code constantly. Stay tuned!

**Comment by townmi** [comment]
very well, good luck.
