### ISSUE TITLE
Unable to run - version not found: tns-core-modules@1.3.0

### ISSUE THREAD

**Issue by darshanrampatel** [NativeScript/sample-Tasks#24]
Fails on both Windows and Mac OSX.

Project successfully created.
Command failed: C:\Windows\system32\cmd.exe /s /c "npm install "
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4

npm ERR! version not found: tns-core-modules@1.3.0

**Comment by hamorphis** [comment]
We have not released it yet. I am preparing the app for this version. Currently, you will not be able to run it. When we release 1.3.0 I will make sure the app builds and runs.
