### ISSUE TITLE
Sidedrawer

### ISSUE THREAD

**Issue by dapriett** [NativeScript/sample-Tasks#34]
Hello,

Where can I find this sidedrawer that is featured here on your site?

![Image of Sidebar](https://d2odgkulk9w7if.cloudfront.net/images/default-source/default-album/00-navdrawer.png?sfvrsn=0)

**Comment by vchimev** [comment]
Hello @dapriett,

apologies for the late reply.

The SideDrawer component is free and it is part of [Telerik UI for NativeScript] (https://www.npmjs.com/package/nativescript-telerik-ui). You could find more information about it on [this] (https://www.nativescript.org/blog/welcome-to-telerik-ui-for-nativescript) blog post as well as its documentation [here] (http://docs.telerik.com/devtools/nativescript-ui/Controls/SideDrawer/sidedrawer-overview).

**Comment by dapriett** [comment]
Thanks @vchimev, I had found it.  It's not currently use in this sample though, is it?  I couldn't find a reference to it - is that picture from a different tasks sample somewhere?

**Comment by vchimev** [comment]
@dapriett, for samples with the SideDrawer component you could refer to the [TelerikNext] (https://github.com/NativeScript/sample-TelerikNEXT) application or the NativeScript UI samples application [here] (https://github.com/telerik/nativescript-ui-samples).
