### ISSUE TITLE
not woking with v1.6.1

### ISSUE THREAD

**Issue by Mirodil** [NativeScript/sample-Tasks#46]
not working with v1.6.1, just cloned and run app
![final_bstsnapshot_957301](https://cloud.githubusercontent.com/assets/1898801/13199192/19991d96-d7e4-11e5-9a64-3427b51cb0e0.jpg)

**Comment by rosen-vladimirov** [comment]
Hi @Mirodil , 
Can you try updating the `tns-core-modules` versions:
```
rm -rf node_modules platforms;
npm i --save tns-core-modules@latest;
tns run android
```

**Comment by Mirodil** [comment]
thanks it works
