### ISSUE TITLE
cannot run on android

### ISSUE THREAD

**Issue by ljx0517** [NativeScript/sample-Tasks#48]
build is ok
`BUILD SUCCESSFUL

Total time: 43.96 secs
Project successfully built`

but cannot run
`java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.sampleTasks/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
Calling js method onCreate failed

TypeError: Cannot read property 'widgets' of undefined
File: "/data/data/org.nativescript.sampleTasks/files/app/tns_modules/ui/frame/frame.js, line: 327, column: 39

StackTrace: 
	Frame: function:'NativeActivity.onCreate', file:'/data/data/org.nativescript.sampleTasks/files/app/tns_modules/ui/frame/frame.js', line: 327, column: 40

	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2180)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
	at android.app.ActivityThread.access$600(ActivityThread.java:141)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5041)
	at java.lang.reflect.Method.invoke`

**Comment by appcela** [comment]
## Root Cause

same here using {N} 1.6.2, this is the code that's throwing the error,

### line#327
```
var root = new org.nativescript.widgets.ContentLayout(this);
```

However, this code is not found in {N} 1.6.2 version.

### Incompatible Version

Apparently, this project was written for {N} 1.5.2,

```
// package.json
"dependencies": {
    "sample-tasks-app-options": "file:app_options",
    "tns-core-modules": "1.5.2"
  }
```

## Solution

Change the dependency to use `"tns-core-modules": "1.6.2"` and rebuild the project.

```
// package.json
"dependencies": {
    "sample-tasks-app-options": "file:app_options",
    "tns-core-modules": "1.6.2"
  }
```

**Comment by ljx0517** [comment]
ok~ thx
i will try~
