### ISSUE TITLE
run.bat does not work

### ISSUE THREAD

**Issue by vchimev** [NativeScript/sample-Tasks#7]
The `run.bat` script should run the sample on an Android emulator under Windows.

vchimev@VCHIMEV /c/Work/GitHub/sample-Tasks (master)
$ run.bat
./run.bat: line 1: @echo: command not found
./run.bat: line 2: syntax error near unexpected token `('
./run.bat: line 2: `FOR /f "delims=" %%A IN ('npm list -g nativescript') DO @SET NativeScriptString=%%A'

\* Note in README.md does the `run.bat` script require shell in order to work or not.

**Comment by PanayotCankov** [comment]
The `tns platform add android` also creates a `project.properties` with `target=android-19`, while the app seems to require `target=android-21`. I am not sure if we can automate this now.

**Comment by dtopuzov** [comment]
It should be OK now :)
